### ISSUE TITLE
Decide what this accelerator will do

### ISSUE THREAD

**Issue by zakbutcher** [pariveda-accelerators/react#3]
## Current Options Include:
- Repository of knowledge and a baseline app to get started
- Repository of code snippets and patterns that are useful
- Complete framework for building apps in "the Pariveda way"
- Something else entirely

**Comment by zakbutcher** [comment]
IMO this project should be something in between options 1 & 3.  React is fundamentally a library for building **view** components in the traditional MVC architecture.  The "business logic" that gives react components purpose & functionality should be written in vanilla javascript outside of component scope.

Following this approach enables a few things:
1.  Less React-specific experience is required to get up & running (it's mostly JS after all)
2.  We can build core components that EVERY application needs, thus saving time and effort
3.  We can establish our own best practices that evolve with React and eventually give back to the React community

**Comment by lanesawyer** [comment]
Love the idea, and I think there's a lot of boilerplate stuff like this that we do as a firm, and we could save a lot of time setting this up right! Got a lot of questions, and they're all over the place:

1. Is this open source?
2. Is this formally affiliated with Pariveda or something Pariveda employees happen to be doing? If the former, why not use the existing Pariveda Github account? If the latter, can we separate it from Pariveda completely and just start an open-source project that happens to be run by Fins?
3. How does code ownership work when using these templates for client work? Could we ever use work done towards a client project to improve the accelerator, and if so, does that create legal issues on ownership?
4. How do we keep this effort from dying like past attempts (for example, see the Sailboat repository in the Github Pariveda account)?
5. Are these template just a starting point for projects, forked once and never referenced again, or is this supposed to be a sort of library that can be updated and have those updates be pushed to projects previously generated from this template?
6. I see a few different UI libraries implemented. Why provide different versions of buttons/inputs/etc.? Can we instead choose one core UI library to develop, create a strong interface for each one, and if the needs of a project are different enough they can implement their own UI library based on the interface instead of the devs maintaining multiple different libraries?

I'm sure I have more questions, but I'm very interested in this effort!

Personally, I think Pariveda could use some Fins that are internal consultants who work on things like this accelerator project to speed up all the client-facing Fins. Imagine having the role of joining a project team to observe them, provide recommendations for process improvements, and then enabling them by developing tools that will help client work go faster. I would love that job and I think it would make us a much more effective company. Some might argue that's part of the job of Internal IT, but I think of them as running Pariveda as a business, not as a group that necessarily enables the Consulting circle in the way I want.

Anyway, pipe-dream aside, I'm looking forward to seeing what we do with this!

**Comment by zakbutcher** [comment]
> Is this open source?

I think the spirit of what we're doing is "yes" or maybe "internally open source."  I'm open to either, but I'm leaning towards fully open source

> Is this formally affiliated with Pariveda or something Pariveda employees happen to be doing? If the former, why not use the existing Pariveda Github account? If the latter, can we separate it from Pariveda completely and just start an open-source project that happens to be run by Fins?

This is probably a better question for @manwaring.  As of now, this is closer to the latter.  I'm personally ok with separating the two.  That being said, the initial impetus was to create accelerators *for use by Pariveda* to accelerate delivery of projects.  So there's definitely a link to delivering more value as a company, not just providing another resource for the community to build apps with.

> How does code ownership work when using these templates for client work? Could we ever use work done towards a client project to improve the accelerator, and if so, does that create legal issues on ownership?

This is another one @manwaring could probably weigh in on.  Ideally we should incorporate lessons learned, best practices, or perspectives from client work into these accelerators.

> How do we keep this effort from dying like past attempts (for example, see the Sailboat repository in the Github Pariveda account)?

Accountability?  I think having a clear outline of what we want these accelerators to be and assigning responsibility are two key steps towards making sure these efforts don't die out.  I also think we should start with very focused goals and use issues to identify future features

> Are these template just a starting point for projects, forked once and never referenced again, or is this supposed to be a sort of library that can be updated and have those updates be pushed to projects previously generated from this template?

I foresee multiple approaches down the line.  Initially, these templates would be used to generate boilerplate for a project, similar to Create React App.  Eventually, other repositories can be created to provide additional, long-term value such as a component library or libraries with additional components if the client needs additional tooling like Redux, TS, etc

> I see a few different UI libraries implemented. Why provide different versions of buttons/inputs/etc.? Can we instead choose one core UI library to develop, create a strong interface for each one, and if the needs of a project are different enough they can implement their own UI library based on the interface instead of the devs maintaining multiple different libraries?

That's something we need to figure out.  The initial work to incorporate a few different component libraries was done to support work on a Gap project in SF.  I don't see a need to keep any of that going forward unless we feel strongly about building a component library.  I see value in doing so, but maintaining a component library comes with additional cost

**Comment by manwaring** [comment]
> Is this formally affiliated with Pariveda or something Pariveda employees happen to be doing? If the former, why not use the existing Pariveda Github account? If the latter, can we separate it from Pariveda completely and just start an open-source project that happens to be run by Fins?

My hypothesis is that having a separate repo will help keep some momentum by virtue of being more focused and having less cruft.  at least when i look through the repos on pariveda github proper i see a lot of... eclectic and unmaintained things.  I wouldn't have a problem moving things over to Pariveda proper or renaming to remove Pariveda.  Everyone that's added to this organization will be made an Admin, so anybody can change things.  (which is another reason I didn't go straight to Pariveda github - permissions there are very 'internal it'

> How does code ownership work when using these templates for client work? Could we ever use work done towards a client project to improve the accelerator, and if so, does that create legal issues on ownership?

100% we should be feeding back into these with lessons learned, refined approaches, etc.  I can't see any legal issues as long as we aren't taking proprietary business logic from clients, which isn't the intent of these repositories anyways

> How do we keep this effort from dying like past attempts (for example, see the Sailboat repository in the Github Pariveda account)?

Idk.  I'm hoping that GitHub is more active than BitBucket.  I'm also hoping that by building a community around accelerators in general (and not just the specific accelerators) that there might be a little bit more critical mass - even if i'm the only one working on serverless starters, for example, at least i'm not the only one working on starters in general.  And i like Zak's idea about accountability - we should share widely and encourage people to use, and then set the expectation with those teams that they contribute back periodically.

As a general note, I think at least the three of us are very aligned in vision and the value we see for work like this.  I have no preconceived notions about what will and won't work, I'm very comfortable starting with what we have and adjusting constantly.  If anyone feels like something could be improved i'm all about people being empowered to make those improvements - i will not get in the way of anyone who is actively working to improve things

**Comment by zakbutcher** [comment]
I think we've got a lot of good discussion points to dive into further, however I think this issue is more focused on *what* we want this accelerator to be, not necessarily about the logistics of working on an open source project.

Based on @lanesawyer's comment in Slack about a drag & drop-style project for building UI's, I think an MVP version of this accelerator would provide the following:

1. Core component library based on Atomic Design (Buttons, Modals, Dropdowns, etc)
2. Tests for all core components
3. TypeScript support
4. Framework for delivering complete web apps (i.e. Next.js)

I personally would add a stretch goal for incorporating text editor configs and plugin recommendations, however I know how touchy some people are when it comes to their text editors

**Comment by zakbutcher** [comment]
Seeing how this convo has gotten a little stale, I think I'll close the discussion and move forward with what I outlined in my previous comment.  If we need to reopen this issue in the future, we will.
